In [7]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

In [5]:
#loading the dataset
df=pd.read_csv(r'C:\NG\customer-churn-prediction\data\customer_churn_business_dataset.csv')

In [6]:
df.head(5)

,customer_id,gender,age,country,city,customer_segment,tenure_months,signup_channel,contract_type,monthly_logins,...,avg_resolution_time,complaint_type,csat_score,escalations,email_open_rate,marketing_click_rate,nps_score,survey_response,referral_count,churn
0,CUST_00001,Male,68,Bangladesh,London,SME,22,Web,Monthly,26,...,13.354360,Service,4.0,0,0.71,0.40,27,Satisfied,1,0
1,CUST_00002,Female,57,Canada,Sydney,Individual,9,Mobile,Monthly,7,...,25.140088,Billing,2.0,0,0.78,0.33,-19,Neutral,2,1
2,CUST_00003,Male,24,Germany,New York,SME,58,Web,Yearly,19,...,27.572928,Service,3.0,0,0.35,0.49,80,Neutral,1,0
3,CUST_00004,Male,49,Australia,Dhaka,Individual,19,Mobile,Yearly,34,...,26.420822,Technical,5.0,1,0.83,0.15,100,Neutral,0,0
4,CUST_00005,Male,65,Bangladesh,Delhi,Individual,52,Web,Monthly,20,...,26.674579,Technical,4.0,0,0.65,0.44,21,Unsatisfied,1,0

In [9]:
df.shape

(10000, 32)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             10000 non-null  str
 1   gender                  10000 non-null  str
 2   age                     10000 non-null  int64
 3   country                 10000 non-null  str
 4   city                    10000 non-null  str
 5   customer_segment        10000 non-null  str
 6   tenure_months           10000 non-null  int64
 7   signup_channel          10000 non-null  str
 8   contract_type           10000 non-null  str
 9   monthly_logins          10000 non-null  int64
 10  weekly_active_days      10000 non-null  int64
 11  avg_session_time        10000 non-null  float64
 12  features_used           10000 non-null  int64
 13  usage_growth_rate       10000 non-null  float64
 14  last_login_days_ago     10000 non-null  int64
 15  monthly_fee             10000 non-null  int64
 16  total_revenue           10000 non-null  int64
 17  payment_method          10000 non-null  str
 18  payment_failures        10000 non-null  int64
 19  discount_applied        10000 non-null  str
 20  price_increase_last_3m  10000 non-null  str
 21  support_tickets         10000 non-null  int64
 22  avg_resolution_time     10000 non-null  float64
 23  complaint_type          7955 non-null   str
 24  csat_score              10000 non-null  float64
 25  escalations             10000 non-null  int64
 26  email_open_rate         10000 non-null  float64
 27  marketing_click_rate    10000 non-null  float64
 28  nps_score               10000 non-null  int64
 29  survey_response         10000 non-null  str
 30  referral_count          10000 non-null  int64
 31  churn                   10000 non-null  int64
dtypes: float64(6), int64(14), str(12)
memory usage: 3.1 MB

In [13]:
#statistical summary of the dataset()
df.describe()

,age,tenure_months,monthly_logins,weekly_active_days,avg_session_time,features_used,usage_growth_rate,last_login_days_ago,monthly_fee,total_revenue,payment_failures,support_tickets,avg_resolution_time,csat_score,escalations,email_open_rate,marketing_click_rate,nps_score,referral_count,churn
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000
mean,45.906100,30.155700,19.672000,3.479400,15.187890,4.990800,0.019423,9.505200,34.930000,1057.018000,0.501000,1.206600,23.953210,3.486700,0.294100,0.499610,0.253575,19.110500,0.9922,0.102100
std,16.420416,17.099517,9.838003,2.302283,6.830774,2.211607,0.149567,9.799417,23.785115,1020.148233,0.711934,1.104554,9.956999,0.978631,0.543171,0.231601,0.140532,38.936619,0.9939,0.302795
min,18.000000,1.000000,0.000000,0.000000,1.000000,1.000000,-0.580000,0.000000,10.000000,10.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.100000,0.010000,-100.000000,0.0000,0.000000
25%,32.000000,16.000000,13.000000,1.000000,10.391645,3.000000,-0.080000,2.000000,20.000000,340.000000,0.000000,0.000000,17.082041,3.000000,0.000000,0.300000,0.130000,-7.000000,0.0000,0.000000
50%,46.000000,30.000000,20.000000,3.000000,15.161659,5.000000,0.020000,6.000000,30.000000,720.000000,0.000000,1.000000,23.950444,4.000000,0.000000,0.500000,0.250000,19.000000,1.0000,0.000000
75%,60.000000,45.000000,26.000000,5.000000,19.882034,6.000000,0.120000,13.000000,50.000000,1440.000000,1.000000,2.000000,30.758480,4.000000,1.000000,0.700000,0.380000,46.000000,2.0000,0.000000
max,74.000000,59.000000,54.000000,7.000000,41.996411,15.000000,0.540000,80.000000,100.000000,5900.000000,5.000000,7.000000,61.821878,5.000000,4.000000,0.900000,0.500000,100.000000,7.0000,1.000000

In [20]:
#checking for missing values
(df.isnull().sum()/len(df)*100).sort_values(ascending = False)

complaint_type            20.45
customer_id                0.00
age                        0.00
gender                     0.00
city                       0.00
customer_segment           0.00
tenure_months              0.00
country                    0.00
contract_type              0.00
monthly_logins             0.00
weekly_active_days         0.00
avg_session_time           0.00
features_used              0.00
usage_growth_rate          0.00
last_login_days_ago        0.00
signup_channel             0.00
monthly_fee                0.00
total_revenue              0.00
payment_failures           0.00
payment_method             0.00
discount_applied           0.00
price_increase_last_3m     0.00
support_tickets            0.00
avg_resolution_time        0.00
csat_score                 0.00
escalations                0.00
email_open_rate            0.00
marketing_click_rate       0.00
nps_score                  0.00
survey_response            0.00
referral_count             0.00
churn                      0.00
dtype: float64

In [24]:
#checking for duplicates
print(df.duplicated().sum())

0

In [27]:
# Target distribution
churn_counts = df['churn'].value_counts()
churn_pct = df['churn'].value_counts(normalize=True) * 100

In [28]:
print("Churn Distribution:")
print(churn_counts)
print(f"\nPercentage:")
print(churn_pct)

Churn Distribution:
churn
0    8979
1    1021
Name: count, dtype: int64

Percentage:
churn
0    89.79
1    10.21
Name: proportion, dtype: float64

In [30]:
#insight:
##  data is imbalanced with 89.79% of customers not churning and 10.21% churning.